app:
  baseUrl: ${APP_BASE_URL}
  packages: all

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen: ':7007'

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl:
        rejectUnauthorized: false

  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

catalog:
  providers:
    githubDiscovery:
      kndkhoa:
        type: github-discovery
        url: https://github.com/kndkhoa/*/blob/main/catalog-info.yaml
        schedule:
          frequency: { minutes: 10 }
          timeout: { minutes: 3 }

  rules:
    - allow: [Component, System, API, Resource, Location, Template]

  locations:
    - type: file
      target: ./examples/entities.yaml

    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./examples/springboot-template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]

    - type: url
      target: https://github.com/kndkhoa/talentradar/blob/main/catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location]
